import mongoose from 'mongoose';

import { Product } from '@products/models/product';
import { type Lang } from '@utils/$t';
import { getEnvSecure } from '@utils/getEnvSecure';

try {
  await mongoose.connect(getEnvSecure('DB_URL'), {
    serverApi: {
      version: '1',
      strict: true,
      deprecationErrors: true,
    },
  });

  await Product.insertMany(getProducts());
  mongoose.connection.close();
} catch (e) {
  console.log(e);
}

function getProducts(): { name: Record<Lang, string>; category: string }[] {
  return [
    { name: { 'en-US': 'Ackee', 'pl-PL': 'Ackee' }, category: '' },
    { name: { 'en-US': 'Allspice', 'pl-PL': 'Ziele angielskie' }, category: '' },
    { name: { 'en-US': 'Almond Extract', 'pl-PL': 'Extrakt z migdałów' }, category: '' },
    { name: { 'en-US': 'Almond Milk', 'pl-PL': 'Mleko migdałowe' }, category: '' },
    { name: { 'en-US': 'Almonds', 'pl-PL': 'Migdały' }, category: '' },
    { name: { 'en-US': 'Ancho Chillies', 'pl-PL': 'Ancho Chilli' }, category: '' },
    { name: { 'en-US': 'Anchovy Fillet', 'pl-PL': 'Filet z anchois' }, category: '' },
    { name: { 'en-US': 'Apple Cider Vinegar', 'pl-PL': 'Ocet jabłkowy' }, category: '' },
    { name: { 'en-US': 'Apple', 'pl-PL': 'Jabłko' }, category: '' },
    { name: { 'en-US': 'Apricot', 'pl-PL': 'Morela' }, category: '' },
    { name: { 'en-US': 'Apricot Jam', 'pl-PL': 'Dżem morelowy' }, category: '' },
    { name: { 'en-US': 'Asparagus', 'pl-PL': 'Szparagi' }, category: '' },
    { name: { 'en-US': 'Aubergine', 'pl-PL': 'Bakłażan' }, category: '' },
    { name: { 'en-US': 'Avocado', 'pl-PL': 'Awokado' }, category: '' },
    { name: { 'en-US': 'Plum Tomato', 'pl-PL': 'Pomidor śliwkowy' }, category: '' },
    { name: { 'en-US': 'Bacon', 'pl-PL': 'Bekon' }, category: '' },
    { name: { 'en-US': 'Baguette', 'pl-PL': 'Bagietka' }, category: '' },
    { name: { 'en-US': 'Baked Beans', 'pl-PL': 'Pieczona fasola' }, category: '' },
    { name: { 'en-US': 'Baking Powder', 'pl-PL': 'Proszek do pieczenia' }, category: '' },
    { name: { 'en-US': 'Balsamic Vinegar', 'pl-PL': 'Ocet balsamiczny' }, category: '' },
    { name: { 'en-US': 'Banana', 'pl-PL': 'Banan' }, category: '' },
    { name: { 'en-US': 'Barbeque Sauce', 'pl-PL': 'Sos barbecue' }, category: '' },
    { name: { 'en-US': 'Basil', 'pl-PL': 'Bazylia' }, category: '' },
    { name: { 'en-US': 'Basmati Rice', 'pl-PL': 'Ryż basmati' }, category: '' },
    { name: { 'en-US': 'Bay Leaf', 'pl-PL': 'Liść laurowy' }, category: '' },
    { name: { 'en-US': 'Bean Sprouts', 'pl-PL': 'Kiełki fasoli' }, category: '' },
    { name: { 'en-US': 'Beef', 'pl-PL': 'Wołowina' }, category: '' },
    { name: { 'en-US': 'Beef Brisket', 'pl-PL': 'Mostek wołowy' }, category: '' },
    { name: { 'en-US': 'Beef Fillet', 'pl-PL': 'Polędwica wołowa' }, category: '' },
    { name: { 'en-US': 'Beef Gravy', 'pl-PL': 'Sos wołowy' }, category: '' },
    { name: { 'en-US': 'Beef Kidney', 'pl-PL': 'Nerki wołowe' }, category: '' },
    { name: { 'en-US': 'Beef Shin', 'pl-PL': 'Wołowina Shin' }, category: '' },
    { name: { 'en-US': 'Beef Stock', 'pl-PL': 'Wywar wołowy' }, category: '' },
    { name: { 'en-US': 'Beef Stock Concentrate', 'pl-PL': 'Koncentrat bulionu wołowego' }, category: '' },
    { name: { 'en-US': 'Beetroot', 'pl-PL': 'Burak' }, category: '' },
    { name: { 'en-US': 'Bicarbonate Of Soda', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Biryani Masala', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Black Beans', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Blackberries', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Black Olives', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Black Pepper', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Black Pudding', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Black Treacle', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Blueberries', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Blue Food Colouring', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Boiling Water', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Borlotti Beans', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Bouquet Garni', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Bowtie Pasta', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Braeburn Apples', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Bramley Apples', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Brandy', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Bread', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Breadcrumbs', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Bread Rolls', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Brie', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Broad Beans', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Broccoli', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Brown Lentils', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Brown Rice', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Brown Sugar', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Brussels Sprouts', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Buckwheat', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Bulgur Wheat', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Bun', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Buns', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Butter', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Butter Beans', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Butternut Squash', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cabbage', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cacao', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cajun', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Candied Peel', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Canned Tomatoes', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cannellini Beans', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Canola Oil', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Capers', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Caramel', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Caramel Sauce', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Caraway Seed', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cardamom', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Carrots', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cashew Nuts', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cashews', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Caster Sugar', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cayenne Pepper', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Celeriac', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Celery', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Celery Salt', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Challots', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Charlotte Potatoes', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cheddar Cheese', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cheese', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cheese Curds', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cheese Slices', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cherry', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cherry Tomatoes', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chestnut Mushroom', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chestnuts', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chicken', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chicken Breast', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chicken Breasts', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chicken Legs', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chicken Stock', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chicken Stock Concentrate', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chicken Stock Cube', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chicken Thighs', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chickpeas', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chili Powder', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chilled Butter', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chilli', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chilli Powder', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chinese Broccoli', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chives', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chocolate Chips', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chopped Onion', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chopped Parsley', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chopped Tomatoes', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Chorizo', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Christmas Pudding', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Ciabatta', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cider', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cilantro', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cinnamon', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cinnamon Stick', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Clams', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Clotted Cream', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cloves', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cocoa', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Coconut Cream', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Coconut Milk', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Coco Sugar', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cod', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Colby Jack Cheese', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cold Water', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Condensed Milk', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cooking wine', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Coriander', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Coriander Leaves', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Coriander Seeds', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Corn Flour', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cornstarch', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Corn Tortillas', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Courgettes', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Couscous', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cream', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cream Cheese', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Creamed Corn', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Creme Fraiche', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Crusty Bread', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cubed Feta Cheese', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cucumber', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cumin', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Cumin Seeds', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Currants', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Curry Powder', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Custard', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Custard Powder', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Dark Brown Soft Sugar', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Dark Brown Sugar', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Dark Chocolate', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Dark Chocolate Chips', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Dark Rum', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Dark Soft Brown Sugar', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Dark Soy Sauce', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Demerara Sugar', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Desiccated Coconut', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Diced Tomatoes', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Digestive Biscuits', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Dijon Mustard', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Dill', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Dill Pickles', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Doner Meat', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Doubanjiang', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Double Cream', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Dried Apricots', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Dried Fruit', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Dried Oregano', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Dry White Wine', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Duck', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Duck Fat', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Duck Legs', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Duck Sauce', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Egg', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Egg Plants', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Egg Rolls', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Eggs', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Egg White', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Egg Yolks', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Enchilada Sauce', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'English Muffins', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'English Mustard', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Extra Virgin Olive Oil', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Fajita Seasoning', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Farfalle', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Fennel', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Fennel Bulb', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Fennel Seeds', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Fenugreek', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Fermented Black Beans', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Feta', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Fettuccine', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Fideo', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Figs', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Filo Pastry', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Fish Sauce', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Fish Stock', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Flaked Almonds', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Flax Eggs', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Flour', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Flour Tortilla', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Floury Potatoes', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Free-range Egg', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'French Lentils', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Fresh Basil', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Freshly Chopped Parsley', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Fresh Thyme', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Fries', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Fromage Frais', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Frozen Peas', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Fruit Mix', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Full Fat Yogurt', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Garam Masala', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Garlic', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Garlic Clove', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Garlic Powder', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Garlic Sauce', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Gelatine Leafs', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Ghee', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Gherkin Relish', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Ginger', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Ginger Cordial', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Ginger Garlic Paste', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Ginger Paste', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Glace Cherry', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Goat Meat', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Goats Cheese', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Gochujang', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Golden Syrup', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Goose Fat', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Gouda Cheese', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Grand Marnier', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Granulated Sugar', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Grape Tomatoes', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Greek Yogurt', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Green Beans', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Green Chilli', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Green Olives', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Green Pepper', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Green Red Lentils', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Green Salsa', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Ground Almonds', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Ground Beef', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Ground Cumin', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Ground Ginger', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Ground Pork', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Gruyère', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Haddock', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Ham', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Hard Taco Shells', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Haricot Beans', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Harissa Spice', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Hazlenuts', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Heavy Cream', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Herring', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Honey', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Horseradish', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Hot Beef Stock', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Hotsauce', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Iceberg Lettuce', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Ice Cream', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Icing Sugar', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Italian Fennel Sausages', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Italian Seasoning', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Jalapeno', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Jam', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Jasmine Rice', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Jerk', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Jerusalem Artichokes', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Kale', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Khus Khus', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Kidney Beans', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Kielbasa', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'King Prawns', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Kosher Salt', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Lamb', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Lamb Kidney', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Lamb Leg', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Lamb Loin Chops', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Lamb Mince', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Lamb Shoulder', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Lard', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Lasagne Sheets', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Lean Minced Beef', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Leek', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Lemon', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Lemon Juice', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Lemons', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Lemon Zest', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Lentils', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Lettuce', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Light Brown Soft Sugar', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Light Rum', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Lime', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Linguine Pasta', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Little Gem Lettuce', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Macaroni', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Mackerel', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Madras Paste', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Malt Vinegar', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Maple Syrup', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Marjoram', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Mars Bar', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Marzipan', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Mascarpone', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Massaman Curry Paste', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Mayonnaise', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Medjool Dates', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Meringue Nests', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Milk', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Milk Chocolate', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Minced Beef', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Minced Garlic', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Minced Pork', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Mincemeat', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Miniature Marshmallows', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Mint', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Mirin', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Mixed Grain', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Mixed Peel', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Mixed Spice', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Monkfish', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Monterey Jack Cheese', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Mozzarella', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Mozzarella Balls', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Muffins', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Mulukhiyah', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Muscovado Sugar', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Mushrooms', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Mussels', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Mustard', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Mustard Powder', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Mustard Seeds', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Naan Bread', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Noodles', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Nutmeg', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Oatmeal', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Oats', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Oil', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Olive Oil', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Onion', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Onions', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Onion Salt', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Orange', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Orange Blossom Water', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Orange Zest', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Oregano', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Oxtail', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Oysters', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Oyster Sauce', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Paccheri Pasta', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Paella Rice', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Paneer', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Pappardelle Pasta', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Paprika', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Parma Ham', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Parmesan', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Parmesan Cheese', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Parmigiano-reggiano', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Parsley', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Passata', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Peaches', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Peanut Brittle', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Peanut Butter', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Peanut Cookies', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Peanut Oil', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Peanuts', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Pears', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Peas', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Pecan Nuts', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Pecorino', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Penne Rigate', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Pepper', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Persian Cucumber', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Pickle Juice', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Pilchards', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Pine Nuts', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Pink Food Colouring', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Pinto Beans', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Pita Bread', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Pitted Black Olives', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Plain Chocolate', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Plain Flour', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Plum Tomatoes', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Polish Sausage', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Pork', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Pork Chops', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Potatoe Buns', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Potatoes', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Potato Starch', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Powdered Sugar', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Prawns', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Pretzels', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Prosciutto', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Prunes', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Puff Pastry', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Pumpkin', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Quinoa', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Raisins', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Rapeseed Oil', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Ras el hanout', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Raspberries', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Raspberry Jam', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Raw King Prawns', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Red Chile Flakes', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Red Chilli', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Red Chilli Powder', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Redcurrants', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Red Food Colouring', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Red Onions', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Red Pepper', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Red Pepper Flakes', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Red Snapper', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Red Wine', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Red Wine Jelly', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Red Wine Vinegar', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Refried Beans', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Rhubarb', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Rice', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Rice Krispies', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Rice Noodles', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Rice Stick Noodles', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Rice Vermicelli', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Rice Vinegar', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Rice wine', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Ricotta', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Rigatoni', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Roasted Vegetables', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Rocket', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Rolled Oats', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Rosemary', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Rose water', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Rum', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Saffron', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sage', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sake', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Salmon', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Salsa', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Salt', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Salt Cod', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Salted Butter', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sardines', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sauerkraut', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sausages', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Scallions', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Scotch Bonnet', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sea Salt', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Self-raising Flour', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Semi-skimmed Milk', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sesame Seed', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sesame Seed Burger Buns', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sesame Seed Oil', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Shallots', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sherry', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Shiitake Mushrooms', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Shortcrust Pastry', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Shortening', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Shredded Mexican Cheese', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Shredded Monterey Jack Cheese', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sichuan Pepper', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Single Cream', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Small Potatoes', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Smoked Haddock', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Smoked Paprika', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Smoked Salmon', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Smoky Paprika', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sour Cream', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Soya Milk', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Soy Sauce', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Spaghetti', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Spinach', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Spring Onions', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Squash', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Squid', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sriracha', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Star Anise', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Starch', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Stilton Cheese', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Stir-fry Vegetables', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Stout', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Strawberries', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Suet', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sugar', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sugar Snap Peas', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sultanas', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sun-Dried Tomatoes', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sunflower Oil', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sushi Rice', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Swede', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sweetcorn', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Sweet Potatoes', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Tabasco Sauce', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Tagliatelle', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Tahini', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Tamarind Ball', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Tamarind Paste', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Tarragon Leaves', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Thai Fish Sauce', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Thai Green Curry Paste', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Thai Red Curry Paste', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Thyme', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Tiger Prawns', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Tinned Tomatos', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Toffee Popcorn', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Tofu', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Tomato', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Tomatoes', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Tomato Ketchup', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Tomato Puree', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Tomato Sauce', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Toor Dal', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Tortillas', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Treacle', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Tripe', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Truffle Oil', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Tuna', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Turkey Mince', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Turmeric', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Turmeric Powder', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Turnips', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Udon Noodles', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Unsalted Butter', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Vanilla', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Vanilla Extract', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Veal', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Vegan Butter', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Vegetable Oil', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Vegetable Stock', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Vegetable Stock Cube', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Vermicelli Pasta', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Vinaigrette Dressing', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Vinegar', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Vine Leaves', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Vine Tomatoes', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Walnuts', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Warm Water', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Water', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Water Chestnut', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'White Chocolate', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'White Chocolate Chips', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'White Fish', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'White Fish Fillets', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'White Flour', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'White Vinegar', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'White Wine', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'White Wine Vinegar', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Wholegrain Bread', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Whole Milk', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Whole Wheat', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Wild Mushrooms', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Wonton Skin', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Wood Ear Mushrooms', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Worcestershire Sauce', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Yeast', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Yellow Food Colouring', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Yellow Onion', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Yellow Pepper', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Yogurt', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Yukon Gold Potatoes', 'pl-PL': '' }, category: '' },
    { name: { 'en-US': 'Zucchini', 'pl-PL': '' }, category: '' },
  ];
}
