import mongoose from 'mongoose';

import { Product } from '@products/models/product';
import { type Lang } from '@utils/$t';
import { getEnvSecure } from '@utils/getEnvSecure';

try {
  await mongoose.connect(getEnvSecure('DB_URL'), {
    serverApi: {
      version: '1',
      strict: true,
      deprecationErrors: true,
    },
  });

  await Product.insertMany(getProducts());
  mongoose.connection.close();
} catch (e) {
  console.log(e);
}

function getProducts(): { name: Record<Lang, string>; category: string }[] {
  return [
    { name: { 'en-US': 'Ackee', 'pl-PL': 'Ackee' }, category: '' },
    { name: { 'en-US': 'Allspice', 'pl-PL': 'Ziele angielskie' }, category: '' },
    { name: { 'en-US': 'Almond Extract', 'pl-PL': 'Extrakt z migdałów' }, category: '' },
    { name: { 'en-US': 'Almond Milk', 'pl-PL': 'Mleko migdałowe' }, category: '' },
    { name: { 'en-US': 'Almonds', 'pl-PL': 'Migdały' }, category: '' },
    { name: { 'en-US': 'Ancho Chillies', 'pl-PL': 'Ancho Chilli' }, category: '' },
    { name: { 'en-US': 'Anchovy Fillet', 'pl-PL': 'Filet z anchois' }, category: '' },
    { name: { 'en-US': 'Apple Cider Vinegar', 'pl-PL': 'Ocet jabłkowy' }, category: '' },
    { name: { 'en-US': 'Apple', 'pl-PL': 'Jabłko' }, category: '' },
    { name: { 'en-US': 'Apricot', 'pl-PL': 'Morela' }, category: '' },
    { name: { 'en-US': 'Apricot Jam', 'pl-PL': 'Dżem morelowy' }, category: '' },
    { name: { 'en-US': 'Asparagus', 'pl-PL': 'Szparagi' }, category: '' },
    { name: { 'en-US': 'Aubergine', 'pl-PL': 'Bakłażan' }, category: '' },
    { name: { 'en-US': 'Avocado', 'pl-PL': 'Awokado' }, category: '' },
    { name: { 'en-US': 'Plum Tomato', 'pl-PL': 'Pomidor śliwkowy' }, category: '' },
    { name: { 'en-US': 'Bacon', 'pl-PL': 'Bekon' }, category: '' },
    { name: { 'en-US': 'Baguette', 'pl-PL': 'Bagietka' }, category: '' },
    { name: { 'en-US': 'Baked Beans', 'pl-PL': 'Pieczona fasola' }, category: '' },
    { name: { 'en-US': 'Baking Powder', 'pl-PL': 'Proszek do pieczenia' }, category: '' },
    { name: { 'en-US': 'Balsamic Vinegar', 'pl-PL': 'Ocet balsamiczny' }, category: '' },
    { name: { 'en-US': 'Banana', 'pl-PL': 'Banan' }, category: '' },
    { name: { 'en-US': 'Barbeque Sauce', 'pl-PL': 'Sos barbecue' }, category: '' },
    { name: { 'en-US': 'Basil', 'pl-PL': 'Bazylia' }, category: '' },
    { name: { 'en-US': 'Basmati Rice', 'pl-PL': 'Ryż basmati' }, category: '' },
    { name: { 'en-US': 'Bay Leaf', 'pl-PL': 'Liść laurowy' }, category: '' },
    { name: { 'en-US': 'Bean Sprouts', 'pl-PL': 'Kiełki fasoli' }, category: '' },
    { name: { 'en-US': 'Beef', 'pl-PL': 'Wołowina' }, category: '' },
    { name: { 'en-US': 'Beef Brisket', 'pl-PL': 'Mostek wołowy' }, category: '' },
    { name: { 'en-US': 'Beef Fillet', 'pl-PL': 'Polędwica wołowa' }, category: '' },
    { name: { 'en-US': 'Beef Gravy', 'pl-PL': 'Sos wołowy' }, category: '' },
    { name: { 'en-US': 'Beef Kidney', 'pl-PL': 'Nerki wołowe' }, category: '' },
    { name: { 'en-US': 'Beef Shin', 'pl-PL': 'Wołowina Shin' }, category: '' },
    { name: { 'en-US': 'Beef Stock', 'pl-PL': 'Wywar wołowy' }, category: '' },
    { name: { 'en-US': 'Beef Stock Concentrate', 'pl-PL': 'Bulionu wołowy' }, category: '' },
    { name: { 'en-US': 'Beetroot', 'pl-PL': 'Burak' }, category: '' },
    { name: { 'en-US': 'Bicarbonate Of Soda', 'pl-PL': 'Soda oczyszczona' }, category: '' },
    { name: { 'en-US': 'Biryani Masala', 'pl-PL': 'Biryani Masala' }, category: '' },
    { name: { 'en-US': 'Black Beans', 'pl-PL': 'Czarna fasola' }, category: '' },
    { name: { 'en-US': 'Blackberries', 'pl-PL': 'Jeżyny' }, category: '' },
    { name: { 'en-US': 'Black Olives', 'pl-PL': 'Czarne oliwki' }, category: '' },
    { name: { 'en-US': 'Black Pepper', 'pl-PL': 'Czarny pieprz' }, category: '' },
    { name: { 'en-US': 'Black Pudding', 'pl-PL': 'Kaszanka' }, category: '' },
    { name: { 'en-US': 'Black Treacle', 'pl-PL': 'Czarna melasa' }, category: '' },
    { name: { 'en-US': 'Blueberries', 'pl-PL': 'Jagody' }, category: '' },
    { name: { 'en-US': 'Blue Food Colouring', 'pl-PL': 'Niebieski barwnik spożywczy' }, category: '' },
    { name: { 'en-US': 'Boiling Water', 'pl-PL': 'Wrząca woda' }, category: '' },
    { name: { 'en-US': 'Borlotti Beans', 'pl-PL': 'Fasola Borlotti' }, category: '' },
    { name: { 'en-US': 'Bouquet Garni', 'pl-PL': 'Bouquet Garni' }, category: '' },
    { name: { 'en-US': 'Brandy', 'pl-PL': 'Brandy' }, category: '' },
    { name: { 'en-US': 'Bread', 'pl-PL': 'Chleb' }, category: '' },
    { name: { 'en-US': 'Breadcrumbs', 'pl-PL': 'Bułka tarta' }, category: '' },
    { name: { 'en-US': 'Brie', 'pl-PL': 'Brie' }, category: '' },
    { name: { 'en-US': 'Broad Beans', 'pl-PL': 'Bób' }, category: '' },
    { name: { 'en-US': 'Broccoli', 'pl-PL': 'Brokuł' }, category: '' },
    { name: { 'en-US': 'Brown Lentils', 'pl-PL': 'Soczewica brązowa' }, category: '' },
    { name: { 'en-US': 'Brown Rice', 'pl-PL': 'Ryż brązowy' }, category: '' },
    { name: { 'en-US': 'Brown Sugar', 'pl-PL': 'Cukier brązowy' }, category: '' },
    { name: { 'en-US': 'Brussels Sprouts', 'pl-PL': 'Brukselka' }, category: '' },
    { name: { 'en-US': 'Buckwheat', 'pl-PL': 'Kasza gryczana' }, category: '' },
    { name: { 'en-US': 'Bulgur Wheat', 'pl-PL': 'Kasza bulgur' }, category: '' },
    { name: { 'en-US': 'Bun', 'pl-PL': 'Bułka' }, category: '' },
    { name: { 'en-US': 'Butter', 'pl-PL': 'Masło' }, category: '' },
    { name: { 'en-US': 'Butter Beans', 'pl-PL': 'Fasola półksiężycowata' }, category: '' },
    { name: { 'en-US': 'Butternut Squash', 'pl-PL': 'Dynia piżmowa' }, category: '' },
    { name: { 'en-US': 'Cabbage', 'pl-PL': 'Kapusta' }, category: '' },
    { name: { 'en-US': 'Cacao', 'pl-PL': 'Kakao' }, category: '' },
    { name: { 'en-US': 'Cajun', 'pl-PL': 'Cajun' }, category: '' },
    { name: { 'en-US': 'Canned Tomatoes', 'pl-PL': 'Pomidory w puszce' }, category: '' },
    { name: { 'en-US': 'Cannellini Beans', 'pl-PL': 'Fasola zwyczajna' }, category: '' },
    { name: { 'en-US': 'Canola Oil', 'pl-PL': 'Olej canola' }, category: '' },
    { name: { 'en-US': 'Capers', 'pl-PL': 'Kapary' }, category: '' },
    { name: { 'en-US': 'Caramel', 'pl-PL': 'Karmel' }, category: '' },
    { name: { 'en-US': 'Caramel Sauce', 'pl-PL': 'Sos karmelowy' }, category: '' },
    { name: { 'en-US': 'Caraway Seed', 'pl-PL': 'Kminek' }, category: '' },
    { name: { 'en-US': 'Cardamom', 'pl-PL': 'Kardamon' }, category: '' },
    { name: { 'en-US': 'Carrot', 'pl-PL': 'Marchew' }, category: '' },
    { name: { 'en-US': 'Cashew Nuts', 'pl-PL': 'Orzechy nerkowca' }, category: '' },
    { name: { 'en-US': 'Cayenne Pepper', 'pl-PL': 'Piperz cayenne' }, category: '' },
    { name: { 'en-US': 'Celeriac', 'pl-PL': 'Korzeń selera' }, category: '' },
    { name: { 'en-US': 'Celery', 'pl-PL': 'Seler naciowy' }, category: '' },
    { name: { 'en-US': 'Celery Salt', 'pl-PL': 'Sól selerowa' }, category: '' },
    { name: { 'en-US': 'Challot', 'pl-PL': 'Szalotka' }, category: '' },
    { name: { 'en-US': 'Cheddar Cheese', 'pl-PL': 'Cheddar' }, category: '' },
    { name: { 'en-US': 'Cheese', 'pl-PL': 'Ser żółty' }, category: '' },
    { name: { 'en-US': 'Cherry', 'pl-PL': 'Wiśnia' }, category: '' },
    { name: { 'en-US': 'Cherry Tomatoes', 'pl-PL': 'Pomidorki koktajlowe' }, category: '' },
    { name: { 'en-US': 'Chestnut Mushroom', 'pl-PL': 'Pieczarka' }, category: '' },
    { name: { 'en-US': 'Chestnut', 'pl-PL': 'Kasztan' }, category: '' },
    { name: { 'en-US': 'Chicken', 'pl-PL': 'Kurczak' }, category: '' },
    { name: { 'en-US': 'Chicken Breast', 'pl-PL': 'Pierś z kurczaka' }, category: '' },
    { name: { 'en-US': 'Chicken Legs', 'pl-PL': 'Podudzia kurczaka' }, category: '' },
    { name: { 'en-US': 'Chicken Stock', 'pl-PL': 'Wywar drobiowy' }, category: '' },
    { name: { 'en-US': 'Chicken Stock Concentrate', 'pl-PL': 'Bulion drobiowy' }, category: '' },
    { name: { 'en-US': 'Chicken Stock Cube', 'pl-PL': 'Kostka rosołowa' }, category: '' },
    { name: { 'en-US': 'Chicken Thighs', 'pl-PL': 'Udka z kurczaka' }, category: '' },
    { name: { 'en-US': 'Chickpeas', 'pl-PL': 'Ciecierzyca' }, category: '' },
    { name: { 'en-US': 'Chili Powder', 'pl-PL': 'Chili w proszku' }, category: '' },
    { name: { 'en-US': 'Chilled Butter', 'pl-PL': 'Masło schłodzone' }, category: '' },
    { name: { 'en-US': 'Chilli', 'pl-PL': 'Chili' }, category: '' },
    { name: { 'en-US': 'Chinese Broccoli', 'pl-PL': 'Brokuł chiński' }, category: '' },
    { name: { 'en-US': 'Chives', 'pl-PL': 'Sczypiorek' }, category: '' },
    { name: { 'en-US': 'Chocolate Chips', 'pl-PL': 'Chipsy czekoladowe' }, category: '' },
    { name: { 'en-US': 'Chopped Onion', 'pl-PL': 'Siekana cebula' }, category: '' },
    { name: { 'en-US': 'Chopped Parsley', 'pl-PL': 'Siekana pietruszka' }, category: '' },
    { name: { 'en-US': 'Chopped Tomatoes', 'pl-PL': 'Pomidory krojone' }, category: '' },
    { name: { 'en-US': 'Chorizo', 'pl-PL': 'Chorizo' }, category: '' },
    { name: { 'en-US': 'Ciabatta', 'pl-PL': 'Ciabatta' }, category: '' },
    { name: { 'en-US': 'Cider', 'pl-PL': 'Cydr' }, category: '' },
    { name: { 'en-US': 'Cilantro', 'pl-PL': 'Kolendra' }, category: '' },
    { name: { 'en-US': 'Cinnamon', 'pl-PL': 'Cynamon' }, category: '' },
    { name: { 'en-US': 'Cinnamon Stick', 'pl-PL': 'Laska cynamonu' }, category: '' },
    { name: { 'en-US': 'Clams', 'pl-PL': 'Małże' }, category: '' },
    { name: { 'en-US': 'Clotted Cream', 'pl-PL': 'Gęsta śmietana' }, category: '' },
    { name: { 'en-US': 'Cloves', 'pl-PL': 'Goździki' }, category: '' },
    { name: { 'en-US': 'Coconut Cream', 'pl-PL': 'Śmietanka kokosowa' }, category: '' },
    { name: { 'en-US': 'Coconut Milk', 'pl-PL': 'Mleko kokosowe' }, category: '' },
    { name: { 'en-US': 'Coco Sugar', 'pl-PL': 'Cukier kokosowy' }, category: '' },
    { name: { 'en-US': 'Cod', 'pl-PL': 'Dorsz' }, category: '' },
    { name: { 'en-US': 'Cold Water', 'pl-PL': 'Zimna woda' }, category: '' },
    { name: { 'en-US': 'Condensed Milk', 'pl-PL': 'Mleko skondensowane' }, category: '' },
    { name: { 'en-US': 'Cooking wine', 'pl-PL': 'Wino' }, category: '' },
    { name: { 'en-US': 'Coriander Leaves', 'pl-PL': 'Liście kolendry' }, category: '' },
    { name: { 'en-US': 'Coriander Seeds', 'pl-PL': 'Ziarna kolendry' }, category: '' },
    { name: { 'en-US': 'Corn Flour', 'pl-PL': 'Mąka kukurydziana' }, category: '' },
    { name: { 'en-US': 'Cornstarch', 'pl-PL': 'Skrobia kukurydziana' }, category: '' },
    { name: { 'en-US': 'Corn Tortillas', 'pl-PL': 'Tortilla kukurydziana' }, category: '' },
    { name: { 'en-US': 'Courgettes', 'pl-PL': 'Kabaczek' }, category: '' },
    { name: { 'en-US': 'Couscous', 'pl-PL': 'Kuskus' }, category: '' },
    { name: { 'en-US': 'Cream', 'pl-PL': 'Śmietana' }, category: '' },
    { name: { 'en-US': 'Cream Cheese', 'pl-PL': 'Serek śmietankowy' }, category: '' },
    { name: { 'en-US': 'Creme Fraiche', 'pl-PL': 'Crème fraîche' }, category: '' },
    { name: { 'en-US': 'Cucumber', 'pl-PL': 'Ogórek' }, category: '' },
    { name: { 'en-US': 'Cumin', 'pl-PL': 'Kmin rzymski' }, category: '' },
    { name: { 'en-US': 'Currants', 'pl-PL': 'Porzeczki' }, category: '' },
    { name: { 'en-US': 'Curry Powder', 'pl-PL': 'Curry' }, category: '' },
    { name: { 'en-US': 'Dark Brown Sugar', 'pl-PL': 'Cukier brązowy' }, category: '' },
    { name: { 'en-US': 'Dark Chocolate', 'pl-PL': 'Czekolada gorzka' }, category: '' },
    { name: { 'en-US': 'Dark Chocolate Chips', 'pl-PL': 'Chipsy gorzkiej czekolady' }, category: '' },
    { name: { 'en-US': 'Dark Rum', 'pl-PL': 'Rum ciemny' }, category: '' },
    { name: { 'en-US': 'Dark Soy Sauce', 'pl-PL': 'Sos sojowy ciemny' }, category: '' },
    { name: { 'en-US': 'Demerara Sugar', 'pl-PL': 'Cukier trzcinowy' }, category: '' },
    { name: { 'en-US': 'Desiccated Coconut', 'pl-PL': 'Wiórki kokosowe' }, category: '' },
    { name: { 'en-US': 'Digestive Biscuits', 'pl-PL': 'Herbatniki' }, category: '' },
    { name: { 'en-US': 'Dijon Mustard', 'pl-PL': 'Musztarda Dijon' }, category: '' },
    { name: { 'en-US': 'Dill', 'pl-PL': 'Koper' }, category: '' },
    { name: { 'en-US': 'Dill Pickles', 'pl-PL': 'Ogórek konserwowy' }, category: '' },
    { name: { 'en-US': 'Doner Meat', 'pl-PL': 'Döner kebab' }, category: '' },
    { name: { 'en-US': 'Double Cream', 'pl-PL': 'Śmietana kremowa' }, category: '' },
    { name: { 'en-US': 'Dried Apricots', 'pl-PL': 'Suszone morele' }, category: '' },
    { name: { 'en-US': 'Dried Fruit', 'pl-PL': 'Suszone owoce' }, category: '' },
    { name: { 'en-US': 'Dried Oregano', 'pl-PL': 'Suszone oregano' }, category: '' },
    { name: { 'en-US': 'Dry White Wine', 'pl-PL': 'Wino białe wytrawne' }, category: '' },
    { name: { 'en-US': 'Duck', 'pl-PL': 'Kaczka' }, category: '' },
    { name: { 'en-US': 'Duck Fat', 'pl-PL': 'Tłuszcz kaczy' }, category: '' },
    { name: { 'en-US': 'Duck Legs', 'pl-PL': 'Udko z kaczki' }, category: '' },
    { name: { 'en-US': 'Egg', 'pl-PL': 'Jajo' }, category: '' },
    { name: { 'en-US': 'Egg White', 'pl-PL': 'Białko jaja' }, category: '' },
    { name: { 'en-US': 'Egg Yolks', 'pl-PL': 'Żółtko jaja' }, category: '' },
    { name: { 'en-US': 'English Mustard', 'pl-PL': 'Musztarda angielska' }, category: '' },
    { name: { 'en-US': 'Extra Virgin Olive Oil', 'pl-PL': 'Oliwa extra virgin' }, category: '' },
    { name: { 'en-US': 'Farfalle', 'pl-PL': 'Farfalle' }, category: '' },
    { name: { 'en-US': 'Fennel', 'pl-PL': 'Fenkuł' }, category: '' },
    { name: { 'en-US': 'Fennel Seeds', 'pl-PL': 'Nasiona kopru' }, category: '' },
    { name: { 'en-US': 'Fenugreek', 'pl-PL': 'Kozieradka' }, category: '' },
    { name: { 'en-US': 'Feta', 'pl-PL': 'Feta' }, category: '' },
    { name: { 'en-US': 'Fettuccine', 'pl-PL': 'Makaron Fettuccine' }, category: '' },
    { name: { 'en-US': 'Fideo', 'pl-PL': 'Makaron Fideo' }, category: '' },
    { name: { 'en-US': 'Figs', 'pl-PL': 'Figi' }, category: '' },
    { name: { 'en-US': 'Filo Pastry', 'pl-PL': 'Ciasto filo' }, category: '' },
    { name: { 'en-US': 'Fish Sauce', 'pl-PL': 'Sos rybny' }, category: '' },
    { name: { 'en-US': 'Fish Stock', 'pl-PL': 'Wywar rybny' }, category: '' },
    { name: { 'en-US': 'Flaked Almonds', 'pl-PL': 'Płatki migdałów' }, category: '' },
    { name: { 'en-US': 'Flax Eggs', 'pl-PL': 'Siemię lniane' }, category: '' },
    { name: { 'en-US': 'Flour', 'pl-PL': 'Mąka' }, category: '' },
    { name: { 'en-US': 'Flour Tortilla', 'pl-PL': 'Tortilla pszenna' }, category: '' },
    { name: { 'en-US': 'French Lentils', 'pl-PL': 'Soczewica francuska' }, category: '' },
    { name: { 'en-US': 'Freshly Chopped Parsley', 'pl-PL': 'Natka pietruszka' }, category: '' },
    { name: { 'en-US': 'Fresh Thyme', 'pl-PL': 'Tymianek' }, category: '' },
    { name: { 'en-US': 'Fries', 'pl-PL': 'Frytki' }, category: '' },
    { name: { 'en-US': 'Frozen Peas', 'pl-PL': 'Groszek mrożony' }, category: '' },
    { name: { 'en-US': 'Fruit Mix', 'pl-PL': 'Mix owoców' }, category: '' },
    { name: { 'en-US': 'Full Fat Yogurt', 'pl-PL': 'Pełnotłusty jogurt' }, category: '' },
    { name: { 'en-US': 'Garam Masala', 'pl-PL': 'Garam masala' }, category: '' },
    { name: { 'en-US': 'Garlic', 'pl-PL': 'Czosnek' }, category: '' },
    { name: { 'en-US': 'Garlic Clove', 'pl-PL': 'Ząbek czosnku' }, category: '' },
    { name: { 'en-US': 'Garlic Powder', 'pl-PL': 'Czosnek w proszku' }, category: '' },
    { name: { 'en-US': 'Garlic Sauce', 'pl-PL': 'Sos czosnkowy' }, category: '' },
    { name: { 'en-US': 'Gelatine Leafs', 'pl-PL': 'Liście żelatyny' }, category: '' },
    { name: { 'en-US': 'Ghee', 'pl-PL': 'Masło klarowane' }, category: '' },
    { name: { 'en-US': 'Ginger', 'pl-PL': 'Imbir' }, category: '' },
    { name: { 'en-US': 'Ginger Cordial', 'pl-PL': 'Syrop imbirowy' }, category: '' },
    { name: { 'en-US': 'Ginger Paste', 'pl-PL': 'Pasta imbirowa' }, category: '' },
    { name: { 'en-US': 'Glace Cherry', 'pl-PL': 'Wiśnia kandyzowana' }, category: '' },
    { name: { 'en-US': 'Goat Meat', 'pl-PL': 'Mięso kozie' }, category: '' },
    { name: { 'en-US': 'Goats Cheese', 'pl-PL': 'Ser kozi' }, category: '' },
    { name: { 'en-US': 'Gochujang', 'pl-PL': 'Gochujang' }, category: '' },
    { name: { 'en-US': 'Golden Syrup', 'pl-PL': 'Syrop cukrowy' }, category: '' },
    { name: { 'en-US': 'Goose Fat', 'pl-PL': 'Tłuszcz gęsi' }, category: '' },
    { name: { 'en-US': 'Gouda Cheese', 'pl-PL': 'Ser Gouda' }, category: '' },
    { name: { 'en-US': 'Grand Marnier', 'pl-PL': 'Grand Marnier' }, category: '' },
    { name: { 'en-US': 'Grape Tomatoes', 'pl-PL': 'Pomidorki śliwkowe' }, category: '' },
    { name: { 'en-US': 'Greek Yogurt', 'pl-PL': 'Jogurt grecki' }, category: '' },
    { name: { 'en-US': 'Green Beans', 'pl-PL': 'Fasolka zielona' }, category: '' },
    { name: { 'en-US': 'Green Chilli', 'pl-PL': 'Chili zielone' }, category: '' },
    { name: { 'en-US': 'Green Olives', 'pl-PL': 'Oliwki zielone' }, category: '' },
    { name: { 'en-US': 'Green Pepper', 'pl-PL': 'Pieprz zielony' }, category: '' },
    { name: { 'en-US': 'Green Red Lentils', 'pl-PL': 'Soczewica czerwona' }, category: '' },
    { name: { 'en-US': 'Green Salsa', 'pl-PL': 'Salsa zielona' }, category: '' },
    { name: { 'en-US': 'Ground Almonds', 'pl-PL': 'Mąka migdałowa' }, category: '' },
    { name: { 'en-US': 'Ground Beef', 'pl-PL': 'Mięso mielone wołowe' }, category: '' },
    { name: { 'en-US': 'Ground Cumin', 'pl-PL': 'Kmin rzymski' }, category: '' },
    { name: { 'en-US': 'Ground Ginger', 'pl-PL': 'Imbir mielony' }, category: '' },
    { name: { 'en-US': 'Ground Pork', 'pl-PL': 'Mięso mielone wieprzowe' }, category: '' },
    { name: { 'en-US': 'Gruyère', 'pl-PL': 'Ser Gruyère' }, category: '' },
    { name: { 'en-US': 'Ham', 'pl-PL': 'Szynka' }, category: '' },
    { name: { 'en-US': 'Hard Taco Shells', 'pl-PL': 'Taco' }, category: '' },
    { name: { 'en-US': 'Haricot Beans', 'pl-PL': 'Fasola Haricot' }, category: '' },
    { name: { 'en-US': 'Harissa Spice', 'pl-PL': 'Harissa' }, category: '' },
    { name: { 'en-US': 'Hazlenuts', 'pl-PL': 'Orzech laskowy' }, category: '' },
    { name: { 'en-US': 'Heavy Cream', 'pl-PL': 'Śmietana kwaśna' }, category: '' },
    { name: { 'en-US': 'Herring', 'pl-PL': 'Śledź' }, category: '' },
    { name: { 'en-US': 'Honey', 'pl-PL': 'Miód' }, category: '' },
    { name: { 'en-US': 'Horseradish', 'pl-PL': 'Chrzan' }, category: '' },
    { name: { 'en-US': 'Iceberg Lettuce', 'pl-PL': 'Sałata lodowa' }, category: '' },
    { name: { 'en-US': 'Ice Cream', 'pl-PL': 'Lody' }, category: '' },
    { name: { 'en-US': 'Icing Sugar', 'pl-PL': 'Cukier puder' }, category: '' },
    { name: { 'en-US': 'Italian Fennel Sausages', 'pl-PL': 'Kiełbasa włoska' }, category: '' },
    { name: { 'en-US': 'Italian Seasoning', 'pl-PL': 'Mieszanka przypraw włoskich' }, category: '' },
    { name: { 'en-US': 'Jalapeno', 'pl-PL': 'Jalapeno' }, category: '' },
    { name: { 'en-US': 'Jam', 'pl-PL': 'Dżem' }, category: '' },
    { name: { 'en-US': 'Jasmine Rice', 'pl-PL': 'Ryż jaśminowy' }, category: '' },
    { name: { 'en-US': 'Jerusalem Artichokes', 'pl-PL': 'Topinambur' }, category: '' },
    { name: { 'en-US': 'Kale', 'pl-PL': 'Jarmuż' }, category: '' },
    { name: { 'en-US': 'Kidney Beans', 'pl-PL': 'Fasola nerkowata' }, category: '' },
    { name: { 'en-US': 'Kielbasa', 'pl-PL': 'Kiełbasa' }, category: '' },
    { name: { 'en-US': 'King Prawns', 'pl-PL': 'Krewetki' }, category: '' },
    { name: { 'en-US': 'Kosher Salt', 'pl-PL': 'Sól koszerna' }, category: '' },
    { name: { 'en-US': 'Lamb', 'pl-PL': 'Jagnięcina' }, category: '' },
    { name: { 'en-US': 'Lamb Leg', 'pl-PL': 'Noga jagnięca' }, category: '' },
    { name: { 'en-US': 'Lamb Loin Chops', 'pl-PL': 'Kotlety ze schabu jagnięcego' }, category: '' },
    { name: { 'en-US': 'Lamb Mince', 'pl-PL': 'Mięso mielone jagnięce' }, category: '' },
    { name: { 'en-US': 'Lamb Shoulder', 'pl-PL': 'Łopatka jagnięca' }, category: '' },
    { name: { 'en-US': 'Lard', 'pl-PL': 'Smalec' }, category: '' },
    { name: { 'en-US': 'Lasagne Sheets', 'pl-PL': 'Makaron Lasagne' }, category: '' },
    { name: { 'en-US': 'Leek', 'pl-PL': 'Por' }, category: '' },
    { name: { 'en-US': 'Lemon', 'pl-PL': 'Cytryna' }, category: '' },
    { name: { 'en-US': 'Lemon Juice', 'pl-PL': 'Sok z cytryny' }, category: '' },
    { name: { 'en-US': 'Lemon Zest', 'pl-PL': 'Zest z cytryny' }, category: '' },
    { name: { 'en-US': 'Lentils', 'pl-PL': 'Soczewica' }, category: '' },
    { name: { 'en-US': 'Lettuce', 'pl-PL': 'Sałata' }, category: '' },
    { name: { 'en-US': 'Light Rum', 'pl-PL': 'Rum jasny' }, category: '' },
    { name: { 'en-US': 'Lime', 'pl-PL': 'Limonka' }, category: '' },
    { name: { 'en-US': 'Linguine Pasta', 'pl-PL': 'Makaron Linguine' }, category: '' },
    { name: { 'en-US': 'Little Gem Lettuce', 'pl-PL': 'Sałata rzymska' }, category: '' },
    { name: { 'en-US': 'Macaroni', 'pl-PL': 'Makaron' }, category: '' },
    { name: { 'en-US': 'Mackerel', 'pl-PL': 'Makrea' }, category: '' },
    { name: { 'en-US': 'Malt Vinegar', 'pl-PL': 'Ocet jęczmienny' }, category: '' },
    { name: { 'en-US': 'Maple Syrup', 'pl-PL': 'Syrop klonowy' }, category: '' },
    { name: { 'en-US': 'Marjoram', 'pl-PL': 'Majeranek' }, category: '' },
    { name: { 'en-US': 'Marzipan', 'pl-PL': 'Marcepan' }, category: '' },
    { name: { 'en-US': 'Mascarpone', 'pl-PL': 'Mascarpone' }, category: '' },
    { name: { 'en-US': 'Massaman Curry Paste', 'pl-PL': 'Pasta Massaman Curry' }, category: '' },
    { name: { 'en-US': 'Mayonnaise', 'pl-PL': 'Majonez' }, category: '' },
    { name: { 'en-US': 'Medjool Dates', 'pl-PL': 'Daktyle' }, category: '' },
    { name: { 'en-US': 'Milk', 'pl-PL': 'Mleko' }, category: '' },
    { name: { 'en-US': 'Milk Chocolate', 'pl-PL': 'Mleko czekoladowe' }, category: '' },
    { name: { 'en-US': 'Minced Beef', 'pl-PL': 'Mięso mielone wołowe' }, category: '' },
    { name: { 'en-US': 'Minced Garlic', 'pl-PL': 'Pasta z czosnku' }, category: '' },
    { name: { 'en-US': 'Minced Pork', 'pl-PL': 'Mięso mielone wieprzowe' }, category: '' },
    { name: { 'en-US': 'Mint', 'pl-PL': 'Mięta' }, category: '' },
    { name: { 'en-US': 'Mirin', 'pl-PL': 'Mirin' }, category: '' },
    { name: { 'en-US': 'Mixed Peel', 'pl-PL': 'Skórka pomarańczowa' }, category: '' },
    { name: { 'en-US': 'Monkfish', 'pl-PL': 'Żabnica' }, category: '' },
    { name: { 'en-US': 'Monterey Jack Cheese', 'pl-PL': 'Ser Monterey Jack' }, category: '' },
    { name: { 'en-US': 'Mozzarella', 'pl-PL': 'Mozzarella tarta' }, category: '' },
    { name: { 'en-US': 'Mozzarella Balls', 'pl-PL': 'Mozzarella' }, category: '' },
    { name: { 'en-US': 'Muscovado Sugar', 'pl-PL': 'Cukier Muscovado' }, category: '' },
    { name: { 'en-US': 'Mushrooms', 'pl-PL': 'Grzyby' }, category: '' },
    { name: { 'en-US': 'Mussels', 'pl-PL': 'Mule' }, category: '' },
    { name: { 'en-US': 'Mustard', 'pl-PL': 'Musztarda' }, category: '' },
    { name: { 'en-US': 'Mustard Powder', 'pl-PL': 'Proszek musztardowy' }, category: '' },
    { name: { 'en-US': 'Mustard Seeds', 'pl-PL': 'Gorczyca' }, category: '' },
    { name: { 'en-US': 'Naan Bread', 'pl-PL': 'Chlebek Naan' }, category: '' },
    { name: { 'en-US': 'Noodles', 'pl-PL': 'Makaron' }, category: '' },
    { name: { 'en-US': 'Nutmeg', 'pl-PL': 'Gałka muszkatołowa' }, category: '' },
    { name: { 'en-US': 'Oatmeal', 'pl-PL': 'Płatki owsiane' }, category: '' },
    { name: { 'en-US': 'Oats', 'pl-PL': 'Owies' }, category: '' },
    { name: { 'en-US': 'Oil', 'pl-PL': 'Olej' }, category: '' },
    { name: { 'en-US': 'Olive Oil', 'pl-PL': 'Oliwa' }, category: '' },
    { name: { 'en-US': 'Onion', 'pl-PL': 'Cebula' }, category: '' },
    { name: { 'en-US': 'Onion Salt', 'pl-PL': 'Cebula w proszku' }, category: '' },
    { name: { 'en-US': 'Orange', 'pl-PL': 'Pomarańcza' }, category: '' },
    { name: { 'en-US': 'Orange Zest', 'pl-PL': 'Zest z pomarańczy' }, category: '' },
    { name: { 'en-US': 'Oregano', 'pl-PL': 'Oregano' }, category: '' },
    { name: { 'en-US': 'Oxtail', 'pl-PL': 'Ogon wołowy' }, category: '' },
    { name: { 'en-US': 'Oyster', 'pl-PL': 'Ostryga' }, category: '' },
    { name: { 'en-US': 'Oyster Sauce', 'pl-PL': 'Sos ostrygowy' }, category: '' },
    { name: { 'en-US': 'Paccheri Pasta', 'pl-PL': 'Makaron Paccheri' }, category: '' },
    { name: { 'en-US': 'Paella Rice', 'pl-PL': 'Ryż do Paelli' }, category: '' },
    { name: { 'en-US': 'Paneer', 'pl-PL': 'Ser Paneer' }, category: '' },
    { name: { 'en-US': 'Pappardelle Pasta', 'pl-PL': 'Makaron Pappardelle' }, category: '' },
    { name: { 'en-US': 'Paprika', 'pl-PL': 'Papryka' }, category: '' },
    { name: { 'en-US': 'Parma Ham', 'pl-PL': 'Szynka parmeńska' }, category: '' },
    { name: { 'en-US': 'Parmesan', 'pl-PL': 'Parmezan' }, category: '' },
    { name: { 'en-US': 'Parmigiano-reggiano', 'pl-PL': 'Parmigiano Reggiano' }, category: '' },
    { name: { 'en-US': 'Parsley', 'pl-PL': 'Natka pietruszki' }, category: '' },
    { name: { 'en-US': 'Passata', 'pl-PL': 'Passata pomidorowa' }, category: '' },
    { name: { 'en-US': 'Peaches', 'pl-PL': 'Brzoskwinie' }, category: '' },
    { name: { 'en-US': 'Peanut Brittle', 'pl-PL': 'Krokant' }, category: '' },
    { name: { 'en-US': 'Peanut Butter', 'pl-PL': 'Masło orzechowe' }, category: '' },
    { name: { 'en-US': 'Peanut Cookies', 'pl-PL': 'Ciasteczka orzechowe' }, category: '' },
    { name: { 'en-US': 'Peanut Oil', 'pl-PL': 'Olej z orzechów' }, category: '' },
    { name: { 'en-US': 'Peanuts', 'pl-PL': 'Orzeszki ziemne' }, category: '' },
    { name: { 'en-US': 'Pear', 'pl-PL': 'Gruszka' }, category: '' },
    { name: { 'en-US': 'Peas', 'pl-PL': 'Groszek' }, category: '' },
    { name: { 'en-US': 'Pecan Nuts', 'pl-PL': 'Orzechy pekan' }, category: '' },
    { name: { 'en-US': 'Pecorino', 'pl-PL': 'Pecorino' }, category: '' },
    { name: { 'en-US': 'Penne Rigate', 'pl-PL': 'Makaron pene' }, category: '' },
    { name: { 'en-US': 'Pepper', 'pl-PL': 'Pieprz' }, category: '' },
    { name: { 'en-US': 'Pickle Juice', 'pl-PL': 'Sok z ogórków' }, category: '' },
    { name: { 'en-US': 'Pilchards', 'pl-PL': 'Sardynki' }, category: '' },
    { name: { 'en-US': 'Pine Nuts', 'pl-PL': 'Orzeszki pini' }, category: '' },
    { name: { 'en-US': 'Pink Food Colouring', 'pl-PL': 'Różowy barwnik spożywczy' }, category: '' },
    { name: { 'en-US': 'Pinto Beans', 'pl-PL': 'Fasola pinto' }, category: '' },
    { name: { 'en-US': 'Pita Bread', 'pl-PL': 'Pita' }, category: '' },
    { name: { 'en-US': 'Pitted Black Olives', 'pl-PL': 'Oliwki czarne drylowane' }, category: '' },
    { name: { 'en-US': 'Plain Chocolate', 'pl-PL': 'Gorzka czekolada' }, category: '' },
    { name: { 'en-US': 'Plain Flour', 'pl-PL': 'Mąka uniwersalna' }, category: '' },
    { name: { 'en-US': 'Plum Tomatoes', 'pl-PL': 'Pomidory śliwkowe' }, category: '' },
    { name: { 'en-US': 'Polish Sausage', 'pl-PL': 'Polska kiełbasa' }, category: '' },
    { name: { 'en-US': 'Pork', 'pl-PL': 'Schab' }, category: '' },
    { name: { 'en-US': 'Pork Chops', 'pl-PL': 'Schab z kością' }, category: '' },
    { name: { 'en-US': 'Potatoe Buns', 'pl-PL': 'Bułki ziemniaczane' }, category: '' },
    { name: { 'en-US': 'Potatoes', 'pl-PL': 'Ziemniaki' }, category: '' },
    { name: { 'en-US': 'Potato Starch', 'pl-PL': 'Skrobia ziemniaczana' }, category: '' },
    { name: { 'en-US': 'Powdered Sugar', 'pl-PL': 'Cukier puder' }, category: '' },
    { name: { 'en-US': 'Prawns', 'pl-PL': 'Krewetki' }, category: '' },
    { name: { 'en-US': 'Pretzels', 'pl-PL': 'Precle' }, category: '' },
    { name: { 'en-US': 'Prosciutto', 'pl-PL': 'Szynka prosciutto' }, category: '' },
    { name: { 'en-US': 'Prunes', 'pl-PL': 'Śliwki suszone' }, category: '' },
    { name: { 'en-US': 'Puff Pastry', 'pl-PL': 'Ciasto francuskie' }, category: '' },
    { name: { 'en-US': 'Pumpkin', 'pl-PL': 'Dynia' }, category: '' },
    { name: { 'en-US': 'Quinoa', 'pl-PL': 'Quinoa' }, category: '' },
    { name: { 'en-US': 'Raisins', 'pl-PL': 'Rodzynki' }, category: '' },
    { name: { 'en-US': 'Rapeseed Oil', 'pl-PL': 'Olej rzepakowy' }, category: '' },
    { name: { 'en-US': 'Raspberries', 'pl-PL': 'Maliny' }, category: '' },
    { name: { 'en-US': 'Raspberry Jam', 'pl-PL': 'Dżem malinowy' }, category: '' },
    { name: { 'en-US': 'Raw King Prawns', 'pl-PL': 'Krewetki królewskie' }, category: '' },
    { name: { 'en-US': 'Red Chile Flakes', 'pl-PL': 'Płatki chili' }, category: '' },
    { name: { 'en-US': 'Red Chilli', 'pl-PL': 'Chili' }, category: '' },
    { name: { 'en-US': 'Red Chilli Powder', 'pl-PL': 'Chili w proszku' }, category: '' },
    { name: { 'en-US': 'Redcurrants', 'pl-PL': 'Porzeczki' }, category: '' },
    { name: { 'en-US': 'Red Food Colouring', 'pl-PL': 'Czerwony barwnik spożywczy' }, category: '' },
    { name: { 'en-US': 'Red Onion', 'pl-PL': 'Czerwona cebula' }, category: '' },
    { name: { 'en-US': 'Red Pepper', 'pl-PL': 'Papryka czerwona' }, category: '' },
    { name: { 'en-US': 'Red Snapper', 'pl-PL': 'Lucjan czerwony' }, category: '' },
    { name: { 'en-US': 'Red Wine', 'pl-PL': 'Wino czerwone' }, category: '' },
    { name: { 'en-US': 'Red Wine Vinegar', 'pl-PL': 'Ocet winny' }, category: '' },
    { name: { 'en-US': 'Refried Beans', 'pl-PL': 'Fasola smażona' }, category: '' },
    { name: { 'en-US': 'Rhubarb', 'pl-PL': 'Rabarbar' }, category: '' },
    { name: { 'en-US': 'Rice', 'pl-PL': 'Ryż' }, category: '' },
    { name: { 'en-US': 'Rice Noodles', 'pl-PL': 'Makaron ryżowy' }, category: '' },
    { name: { 'en-US': 'Rice Vinegar', 'pl-PL': 'Ocet ryżowy' }, category: '' },
    { name: { 'en-US': 'Rice wine', 'pl-PL': 'Wino ryżowe' }, category: '' },
    { name: { 'en-US': 'Ricotta', 'pl-PL': 'Ricotta' }, category: '' },
    { name: { 'en-US': 'Rigatoni', 'pl-PL': 'Makaron Rigatoni' }, category: '' },
    { name: { 'en-US': 'Roasted Vegetables', 'pl-PL': 'Pieczone warzywa' }, category: '' },
    { name: { 'en-US': 'Rocket', 'pl-PL': 'Rukola' }, category: '' },
    { name: { 'en-US': 'Rosemary', 'pl-PL': 'Rozmaryn' }, category: '' },
    { name: { 'en-US': 'Rose water', 'pl-PL': 'Woda różana' }, category: '' },
    { name: { 'en-US': 'Rum', 'pl-PL': 'Rum' }, category: '' },
    { name: { 'en-US': 'Saffron', 'pl-PL': 'Szafran' }, category: '' },
    { name: { 'en-US': 'Sage', 'pl-PL': 'Szałwia' }, category: '' },
    { name: { 'en-US': 'Sake', 'pl-PL': 'Sake' }, category: '' },
    { name: { 'en-US': 'Salmon', 'pl-PL': 'Łosoś' }, category: '' },
    { name: { 'en-US': 'Salsa', 'pl-PL': 'Salsa' }, category: '' },
    { name: { 'en-US': 'Salt', 'pl-PL': 'Sól' }, category: '' },
    { name: { 'en-US': 'Salted Butter', 'pl-PL': 'Masło solone' }, category: '' },
    { name: { 'en-US': 'Sardines', 'pl-PL': 'Sardynki' }, category: '' },
    { name: { 'en-US': 'Sauerkraut', 'pl-PL': 'Kapusta kiszona' }, category: '' },
    { name: { 'en-US': 'Scallions', 'pl-PL': 'Szypiorek' }, category: '' },
    { name: { 'en-US': 'Sea Salt', 'pl-PL': 'Sól morska' }, category: '' },
    { name: { 'en-US': 'Self-raising Flour', 'pl-PL': 'Mąka samorosnąca' }, category: '' },
    { name: { 'en-US': 'Semi-skimmed Milk', 'pl-PL': 'Mleko półtłuste' }, category: '' },
    { name: { 'en-US': 'Sesame Seed', 'pl-PL': 'Sezam' }, category: '' },
    { name: { 'en-US': 'Sesame Seed Oil', 'pl-PL': 'Olej sezamowy' }, category: '' },
    { name: { 'en-US': 'Shallot', 'pl-PL': 'Szalotka' }, category: '' },
    { name: { 'en-US': 'Sherry', 'pl-PL': 'Sherry' }, category: '' },
    { name: { 'en-US': 'Shiitake Mushrooms', 'pl-PL': 'Grzyby shiitake' }, category: '' },
    { name: { 'en-US': 'Shortcrust Pastry', 'pl-PL': 'Ciasto kruche' }, category: '' },
    { name: { 'en-US': 'Shortening', 'pl-PL': 'Margaryna' }, category: '' },
    { name: { 'en-US': 'Sichuan Pepper', 'pl-PL': 'Pieprz syczuański' }, category: '' },
    { name: { 'en-US': 'Single Cream', 'pl-PL': 'Śmietana chuda' }, category: '' },
    { name: { 'en-US': 'Small Potatoes', 'pl-PL': 'Małe ziemniaki' }, category: '' },
    { name: { 'en-US': 'Smoked Haddock', 'pl-PL': 'Plamiak' }, category: '' },
    { name: { 'en-US': 'Smoked Paprika', 'pl-PL': 'Wędzona papryka' }, category: '' },
    { name: { 'en-US': 'Smoked Salmon', 'pl-PL': 'Łosoś wędzony' }, category: '' },
    { name: { 'en-US': 'Sour Cream', 'pl-PL': 'Kwaśna śmietana' }, category: '' },
    { name: { 'en-US': 'Soya Milk', 'pl-PL': 'Mleko sojowe' }, category: '' },
    { name: { 'en-US': 'Soy Sauce', 'pl-PL': 'Sos sojowy' }, category: '' },
    { name: { 'en-US': 'Spaghetti', 'pl-PL': 'Makaron Spaghetti' }, category: '' },
    { name: { 'en-US': 'Spinach', 'pl-PL': 'Szpinak' }, category: '' },
    { name: { 'en-US': 'Spring Onions', 'pl-PL': 'Zielona cebulka' }, category: '' },
    { name: { 'en-US': 'Squid', 'pl-PL': 'Kałamarnica' }, category: '' },
    { name: { 'en-US': 'Sriracha', 'pl-PL': 'Sriracha' }, category: '' },
    { name: { 'en-US': 'Star Anise', 'pl-PL': 'Anyż' }, category: '' },
    { name: { 'en-US': 'Starch', 'pl-PL': 'Skrobia' }, category: '' },
    { name: { 'en-US': 'Stilton Cheese', 'pl-PL': 'Ser Stilton' }, category: '' },
    { name: { 'en-US': 'Stir-fry Vegetables', 'pl-PL': 'Warzywa na patelnie' }, category: '' },
    { name: { 'en-US': 'Stout', 'pl-PL': 'Stout' }, category: '' },
    { name: { 'en-US': 'Strawberries', 'pl-PL': 'Truskawki' }, category: '' },
    { name: { 'en-US': 'Suet', 'pl-PL': 'Łój' }, category: '' },
    { name: { 'en-US': 'Sugar', 'pl-PL': 'Cukier' }, category: '' },
    { name: { 'en-US': 'Sugar Snap Peas', 'pl-PL': 'Groszek cukrowy' }, category: '' },
    { name: { 'en-US': 'Sun-Dried Tomatoes', 'pl-PL': 'Pomidory suszone' }, category: '' },
    { name: { 'en-US': 'Sunflower Oil', 'pl-PL': 'Olej słonecznikowy' }, category: '' },
    { name: { 'en-US': 'Sushi Rice', 'pl-PL': 'Ryż do sushi' }, category: '' },
    { name: { 'en-US': 'Swede', 'pl-PL': 'Brukiew' }, category: '' },
    { name: { 'en-US': 'Sweetcorn', 'pl-PL': 'Kukurydza' }, category: '' },
    { name: { 'en-US': 'Sweet Potato', 'pl-PL': 'Batat' }, category: '' },
    { name: { 'en-US': 'Tabasco Sauce', 'pl-PL': 'Sos Tabasco' }, category: '' },
    { name: { 'en-US': 'Tagliatelle', 'pl-PL': 'Makaron Tagliatelle' }, category: '' },
    { name: { 'en-US': 'Tahini', 'pl-PL': 'Tahini' }, category: '' },
    { name: { 'en-US': 'Tamarind Paste', 'pl-PL': 'Pasta z tamaryndowca' }, category: '' },
    { name: { 'en-US': 'Tarragon Leaves', 'pl-PL': 'Estragon' }, category: '' },
    { name: { 'en-US': 'Thai Green Curry Paste', 'pl-PL': 'Zielona pasta curry' }, category: '' },
    { name: { 'en-US': 'Thai Red Curry Paste', 'pl-PL': 'Czerwona pasta curry' }, category: '' },
    { name: { 'en-US': 'Thyme', 'pl-PL': 'Tymianek' }, category: '' },
    { name: { 'en-US': 'Tiger Prawns', 'pl-PL': 'Krewetki tygrysie' }, category: '' },
    { name: { 'en-US': 'Tinned Tomatos', 'pl-PL': 'Pomidory w puszce' }, category: '' },
    { name: { 'en-US': 'Toffee Popcorn', 'pl-PL': 'Popcorn karmelowy' }, category: '' },
    { name: { 'en-US': 'Tofu', 'pl-PL': 'Tofu' }, category: '' },
    { name: { 'en-US': 'Tomato', 'pl-PL': 'Pomidor' }, category: '' },
    { name: { 'en-US': 'Tomato Ketchup', 'pl-PL': 'Ketchup' }, category: '' },
    { name: { 'en-US': 'Tomato Puree', 'pl-PL': 'Koncentrat pomidorowy' }, category: '' },
    { name: { 'en-US': 'Tomato Sauce', 'pl-PL': 'Sos pomidorowy' }, category: '' },
    { name: { 'en-US': 'Tortilla', 'pl-PL': 'Tortilla' }, category: '' },
    { name: { 'en-US': 'Treacle', 'pl-PL': 'Melasa' }, category: '' },
    { name: { 'en-US': 'Tripe', 'pl-PL': 'Flaki' }, category: '' },
    { name: { 'en-US': 'Truffle Oil', 'pl-PL': 'Olej truflowy' }, category: '' },
    { name: { 'en-US': 'Tuna', 'pl-PL': 'Tuńczyk' }, category: '' },
    { name: { 'en-US': 'Turkey Mince', 'pl-PL': 'Mięso mielone z indyka' }, category: '' },
    { name: { 'en-US': 'Turmeric', 'pl-PL': 'Kurkuma' }, category: '' },
    { name: { 'en-US': 'Turmeric Powder', 'pl-PL': 'Kurkuma w proszku' }, category: '' },
    { name: { 'en-US': 'Turnip', 'pl-PL': 'Rzepa' }, category: '' },
    { name: { 'en-US': 'Udon Noodles', 'pl-PL': 'Makaron udon' }, category: '' },
    { name: { 'en-US': 'Unsalted Butter', 'pl-PL': 'Masło niesolone' }, category: '' },
    { name: { 'en-US': 'Vanilla', 'pl-PL': 'Wanilia' }, category: '' },
    { name: { 'en-US': 'Vanilla Extract', 'pl-PL': 'Ekstrakt z wanilii' }, category: '' },
    { name: { 'en-US': 'Veal', 'pl-PL': 'Cielęcina' }, category: '' },
    { name: { 'en-US': 'Vegan Butter', 'pl-PL': 'Masło wegańskie' }, category: '' },
    { name: { 'en-US': 'Vegetable Oil', 'pl-PL': 'Olej roślinny' }, category: '' },
    { name: { 'en-US': 'Vegetable Stock', 'pl-PL': 'Wywar warzywny' }, category: '' },
    { name: { 'en-US': 'Vegetable Stock Cube', 'pl-PL': 'Kostka rosołowa warzywna' }, category: '' },
    { name: { 'en-US': 'Vermicelli Pasta', 'pl-PL': 'Makaron vermicelli' }, category: '' },
    { name: { 'en-US': 'Vinaigrette Dressing', 'pl-PL': 'Vinegrette' }, category: '' },
    { name: { 'en-US': 'Vinegar', 'pl-PL': 'Ocet' }, category: '' },
    { name: { 'en-US': 'Vine Leaves', 'pl-PL': 'Liście winogron' }, category: '' },
    { name: { 'en-US': 'Vine Tomatoes', 'pl-PL': 'Pomidorki koktajlowe' }, category: '' },
    { name: { 'en-US': 'Walnuts', 'pl-PL': 'Oczechy włoskie' }, category: '' },
    { name: { 'en-US': 'Warm Water', 'pl-PL': 'Ciepła woda' }, category: '' },
    { name: { 'en-US': 'Water', 'pl-PL': 'Woda' }, category: '' },
    { name: { 'en-US': 'White Chocolate', 'pl-PL': 'Biała czekolada' }, category: '' },
    { name: { 'en-US': 'White Chocolate Chips', 'pl-PL': 'Chipsy z białej czekolady' }, category: '' },
    { name: { 'en-US': 'White Fish', 'pl-PL': 'Ryba biała' }, category: '' },
    { name: { 'en-US': 'White Fish Fillet', 'pl-PL': 'Filet z białej ryby' }, category: '' },
    { name: { 'en-US': 'White Flour', 'pl-PL': 'Mąka pszenna' }, category: '' },
    { name: { 'en-US': 'White Vinegar', 'pl-PL': 'Ocet spirytusowy' }, category: '' },
    { name: { 'en-US': 'White Wine', 'pl-PL': 'Białe wino' }, category: '' },
    { name: { 'en-US': 'White Wine Vinegar', 'pl-PL': 'Ocen winny biały' }, category: '' },
    { name: { 'en-US': 'Wholegrain Bread', 'pl-PL': 'Pieczywo pełnoziarniste' }, category: '' },
    { name: { 'en-US': 'Whole Milk', 'pl-PL': 'Pełnotłuste mleko' }, category: '' },
    { name: { 'en-US': 'Whole Wheat', 'pl-PL': 'Mąka pszenna razowa' }, category: '' },
    { name: { 'en-US': 'Wild Mushrooms', 'pl-PL': 'Grzyby' }, category: '' },
    { name: { 'en-US': 'Wood Ear Mushrooms', 'pl-PL': 'Grzyby leśne' }, category: '' },
    { name: { 'en-US': 'Worcestershire Sauce', 'pl-PL': 'Sos Worcestershire' }, category: '' },
    { name: { 'en-US': 'Yeast', 'pl-PL': 'Drożdże' }, category: '' },
    { name: { 'en-US': 'Yellow Food Colouring', 'pl-PL': 'Barwnik spożywczy żółty' }, category: '' },
    { name: { 'en-US': 'Yellow Onion', 'pl-PL': 'Żółta cebula' }, category: '' },
    { name: { 'en-US': 'Yellow Pepper', 'pl-PL': 'Żółta papryka' }, category: '' },
    { name: { 'en-US': 'Yogurt', 'pl-PL': 'Jogurt' }, category: '' },
    { name: { 'en-US': 'Zucchini', 'pl-PL': 'Cukinia' }, category: '' },
  ];
}
